// Package golden provides the reusable golden-file pattern: test cases are
// written in Go and each result is pinned to a reviewed YAML golden file.
// Updates are refused in CI, and updated files are tracked so orphan goldens
// can be cleaned after a full update run.
//
// # Snapshot tests
//
// Write the cases in code and assert each result against a golden file with
// [Snapshot]. The case Name selects the golden file (dir/<name>.golden.yaml):
//
//	func TestReplay(t *testing.T) {
//	    golden.Snapshot(t, "testdata", []golden.Case[MyInput]{
//	        {Name: "empty", In: MyInput{}},
//	        {Name: "typical", In: MyInput{Rows: 3}},
//	    }, func(t *testing.T, in MyInput) MyOutput {
//	        return run(in)
//	    })
//	}
//
// Case "typical" asserts against testdata/typical.golden.yaml; each case is a
// subtest, so -run selects one by name.
//
// # Standalone assertions
//
// [Assert] compares typed values (golden unmarshaled into T). [AssertAny]
// re-parses BOTH sides into `any` before comparing, so key-order/formatting
// churn never produces spurious diffs — goldenbox state goldens use it.
//
// Refresh golden files with:
//
//	go test ./... -update-golden
package golden

import (
	"flag"
	"os"
	"path/filepath"
	"sync"
	"testing"

	"github.com/google/go-cmp/cmp"
	"gopkg.in/yaml.v3"
)

var update = flag.Bool("update-golden", false, "update golden files with actual test output")

// GeneratedHeader marks written goldens as machine-generated. A YAML comment,
// so it is ignored when the golden is read back.
const GeneratedHeader = "# Code generated by \"go test -update-golden\"; DO NOT EDIT.\n\n"

// Updating reports whether this run rewrites goldens (-update-golden).
func Updating() bool { return *update }

// written tracks which golden files this -update-golden run (re)wrote, so
// CleanObsolete can delete orphans left behind by renamed tests.
var (
	mu      sync.Mutex
	written = map[string]bool{}
)

// isCI reports whether we're under CI (CI=true). Goldens must never be
// regenerated in CI — they are reviewed artifacts.
func isCI() bool { return os.Getenv("CI") != "" }

// Case is one snapshot case: Name selects its golden file, In is fed to fn.
type Case[F any] struct {
	Name string
	In   F
}

// Snapshot runs fn on each case's input and asserts the result against
// dir/<case.Name>.golden.yaml. Each case is a subtest; -update-golden rewrites
// the goldens.
func Snapshot[F any, T any](t *testing.T, dir string, cases []Case[F], fn func(t *testing.T, in F) T) {
	t.Helper()
	seen := map[string]bool{}
	for _, c := range cases {
		if c.Name == "" {
			t.Fatalf("golden.Snapshot: case with empty Name")
		}
		if seen[c.Name] {
			t.Fatalf("golden.Snapshot: duplicate case name %q (would share one golden)", c.Name)
		}
		seen[c.Name] = true
		t.Run(c.Name, func(t *testing.T) {
			t.Helper()
			got := fn(t, c.In)
			Assert(t, filepath.Join(dir, c.Name+".golden.yaml"), got)
		})
	}
}

// Assert compares got (typed) against the golden at path: the golden is
// unmarshaled into T and compared with go-cmp. With -update-golden it
// (re)writes the golden instead (refused in CI).
func Assert[T any](t testing.TB, path string, got T) {
	t.Helper()

	if *update {
		write(t, path, got)
		t.Logf("updated golden file %s", path)
		return
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read golden file %s (run with -update-golden to create it): %v", path, err)
	}

	var want T
	if err := yaml.Unmarshal(data, &want); err != nil {
		t.Fatalf("failed to parse golden file %s: %v", path, err)
	}

	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("golden file mismatch %s (-want +got):\n%s\n\nRun with -update-golden to update.", path, diff)
	}
}

// AssertAny compares value against the golden at path with BOTH sides
// re-parsed into `any` first, so key-order / formatting churn never produces
// spurious diffs. With -update-golden it (re)writes the golden instead
// (refused in CI). goldenbox state goldens assert through this.
func AssertAny(t testing.TB, path string, value any) {
	t.Helper()

	got, err := yaml.Marshal(value)
	if err != nil {
		t.Fatalf("marshal value for golden %s: %v", path, err)
	}

	if *update {
		write(t, path, value)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %s: %v (run tests with -update-golden to create it)", path, err)
	}

	var wantAny, gotAny any
	if err := yaml.Unmarshal(want, &wantAny); err != nil {
		t.Fatalf("unmarshal golden %s: %v", path, err)
	}
	if err := yaml.Unmarshal(got, &gotAny); err != nil {
		t.Fatalf("unmarshal current value for golden %s: %v", path, err)
	}

	if diff := cmp.Diff(wantAny, gotAny); diff != "" {
		t.Errorf("golden mismatch %s (-want +got):\n%s", path, diff)
	}
}

// write marshals v and (re)writes the golden file, tracking it for
// CleanObsolete. Refused in CI: goldens are reviewed artifacts — regenerate
// locally and commit the diff.
func write[T any](t testing.TB, path string, v T) {
	t.Helper()
	if isCI() {
		t.Fatalf("refusing to update golden %s in CI: goldens are reviewed artifacts, regenerate locally and commit the diff", path)
	}
	data, err := yaml.Marshal(v)
	if err != nil {
		t.Fatalf("failed to marshal golden value: %v", err)
	}
	data = append([]byte(GeneratedHeader), data...)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir for golden %s: %v", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("failed to write golden file %s: %v", path, err)
	}
	mu.Lock()
	written[path] = true
	mu.Unlock()
}

// CleanObsolete deletes golden files under dir that this -update-golden run
// did not (re)write — orphans left behind by renamed or deleted tests. It is a
// no-op unless -update-golden is set and the whole suite ran (no -run filter —
// a filtered run must not treat unrun tests' goldens as orphans). Call it from
// TestMain after m.Run() returns 0. Returns the removed paths.
func CleanObsolete(dir string) []string {
	if !*update {
		return nil
	}
	if f := flag.Lookup("test.run"); f != nil && f.Value.String() != "" {
		return nil
	}
	files, err := filepath.Glob(filepath.Join(dir, "*.golden*.yaml"))
	if err != nil {
		return nil
	}
	mu.Lock()
	defer mu.Unlock()
	var removed []string
	for _, f := range files {
		if !written[f] {
			if os.Remove(f) == nil {
				removed = append(removed, f)
			}
		}
	}
	return removed
}
